[package]
name = "PersistentMarkingLB"
version = "0.1.0"
authors = ["tanguc <sergen.tanguc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2.13", features = ["sync", "macros", "net", "tcp", "stream", "rt-threaded"] }
pretty_env_logger = "0.4.0"
log = "0.4.8"
futures = "0.3.4"
tokio-util = { version = "0.3.0", features = ["codec"] }
