name: Build & Push to DockerHub
on:
  release:
    types:
      - published
jobs:
  push:
    name: Login & Push to DockerHub
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Tag version
        id: slug-version
        run: echo "::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}"
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          tags: ${{ steps.slug-version.outputs.VERSION }}, latest
          labels: ${{ steps.docker-meta.outputs.labels }}
          push: true
          repository: ${{ secrets.DOCKER_REPO }}
