name: Build & Push to DockerHub

on:
  release:
    types:
      - published

jobs:
  push:
    name: Login & Push to DockerHub
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Tag version
        id: slug-version
        run: echo "::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}"
      - name: Prepare repository Docker
        run: |
          echo IMAGE_REPOSITORY=toto >> $GITHUB_ENV
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          context: .
          file: ./Dockerfile
          tags: |
            ${{ secrets.DOCKER_REPO }}:${{ steps.slug-version.outputs.VERSION }}
            ${{ secrets.DOCKER_REPO }}:latest
          push: true
