name: Build and test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Linux Ubuntu 18.04
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2020-08-28
          override: true
          components: rustfmt, clippy
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
      # - name: Run check
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: check
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose
